#!/bin/bash

# Version:
# 1.0: Initial file version
# 1.1: Update links for sbenenll

# file is intended to be in /usr/bin/proxmox-update
# This command retreive the latest version of proxmox-toolbox and execute it with update argument

proxmox-update() {
wget -qO - https://raw.githubusercontent.com/sbennell/SetupProxmox/Testing/files/update.sh | bash /dev/stdin 
}

proxmox-update
